development:
    couchdb: "http://localhost:5984/lilruby"
    lang: "pt"
    connect: "http://localhost:3000"
test:
    couchdb: "http://localhost:5984/lilruby"
    lang: "pt"
    connect: "http://localhost:3000"
production:
    couchdb: "http://localhost:5984/lilruby"
    lang: "pt"
    connect: "http://localhost:3000"
