development:
    couchdb: "http://admin:852640sd@localhost:5984/cncflora"
    lang: "pt"
    connect: "http://localhost:3000"
test:
    couchdb: "http://admin:852640sd@localhost:5984/cncflora"
    lang: "pt"
    connect: "http://localhost:3000"
production:
    couchdb: "http://admin:852640sd@localhost:5984/cncflora"
    lang: "pt"
    connect: "http://localhost:3000"
