development:
    etcd: "http://192.168.50.13:4001"
    db: "cncflora"
    lang: "pt"
    context: "connect"
    base: ""
test:
    etcd: "http://192.168.50.13:4001"
    db: "cncflora_test"
    lang: "pt"
    context: "connect"
    base: ""
production:
    etcd: "http://cncflora.jbrj.gov.br/etcd"
    db: "cncflora"
    lang: "pt"
    context: "connect"
    base: "/assessments"
