development:
    lang: "pt"
    connect: "http://localhost:3000"
    couchdb: "http://tester:tester@localhost:5984/cncflora"
test:
    lang: "pt"
    connect: "http://localhost:3000"
    couchdb: "http://tester:tester@localhost:5984/cncflora_test_assessment"
production:
    lang: "pt"
    connect: "http://localhost:3000"
    couchdb: "http://tester:tester@localhost:5984/cncflora"
