development:
    lang: "pt"
    base: ""
    couchdb: "http://192.168.50.13:5984"
    connect: "http://192.168.50.13:8080"
    connect_url: "http://192.168.50.13:8080"
    elasticsearch: "http://192.168.50.13:9200"
test:
    lang: "pt"
    base: ""
    couchdb: "http://192.168.50.13:5984"
    connect: "http://192.168.50.13:8080"
    connect_url: "http://192.168.50.13:8080"
    elasticsearch: "http://192.168.50.13:9200"
production:
    lang: 'pt'
    couchdb: 'http://$HOST/couchdb'
    connect: 'http://$HOST/connect'
    connect_url: 'http://cncflora.jbrj.gov.br/connect'
    elasticsearch: 'http://$HOST/elasticsearch'
    base: "/assessments"
    occurrences: "http://$HOST/occurrences"
    occurrences_url: "http://cncflora.jbrj.gov.br/occurrences"
    profiles: "http://$HOST/profiles"
    profiles_url: "http://cncflora.jbrj.gov.br/profiles"
