development:
    etcd: "http://192.168.50.13:4001"
    lang: "pt"
    base: ""
test:
    etcd: "http://192.168.50.13:4001"
    lang: "pt"
    base: ""
production:
    etcd: "http://$HOST/etcd"
    lang: "pt"
    base: "/assessments"
